-- MySQL Script generated by MySQL Workbench
-- Mon Sep  5 13:35:05 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`ESCUELA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ESCUELA` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ESCUELA` (
  `PROFESOR` INT NOT NULL,
  `ALUMNO` VARCHAR(45) NULL,
  `MATERIA` VARCHAR(4) NULL,
  PRIMARY KEY (`PROFESOR`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MATERIA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`MATERIA` ;

CREATE TABLE IF NOT EXISTS `mydb`.`MATERIA` (
  `codigo materia` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `version` VARCHAR(45) NOT NULL,
  `grado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo materia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ALUMNO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ALUMNO` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ALUMNO` (
  `identificacion` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `curso` VARCHAR(45) NOT NULL,
  `MATERIA_codigo materia` INT NOT NULL,
  PRIMARY KEY (`identificacion`, `MATERIA_codigo materia`),
  INDEX `fk_ALUMNO_MATERIA1_idx` (`MATERIA_codigo materia` ASC) VISIBLE,
  CONSTRAINT `fk_ALUMNO_MATERIA1`
    FOREIGN KEY (`MATERIA_codigo materia`)
    REFERENCES `mydb`.`MATERIA` (`codigo materia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PROFESOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PROFESOR` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PROFESOR` (
  `c_identificacion` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `ALUMNO_identificacion` INT NOT NULL,
  `ALUMNO_MATERIA_codigo materia` INT NOT NULL,
  PRIMARY KEY (`c_identificacion`),
  INDEX `fk_PROFESOR_ALUMNO1_idx` (`ALUMNO_identificacion` ASC, `ALUMNO_MATERIA_codigo materia` ASC) VISIBLE,
  CONSTRAINT `fk_PROFESOR_ALUMNO1`
    FOREIGN KEY (`ALUMNO_identificacion` , `ALUMNO_MATERIA_codigo materia`)
    REFERENCES `mydb`.`ALUMNO` (`identificacion` , `MATERIA_codigo materia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
